name: cochl_sense
version: 1.1.0
description: API Library for Dart with audio analysis and recognition solutions from Cochlear.ai
homepage: https://github.com/cochlearai/sense-dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  grpc: ^2.1.3
  protobuf: ^1.0.1
  fixnum: ^0.10.0

dev_dependencies:
